services:
  postgres:
    container_name: pg-container
    image: postgres
    ports:
      - "5430:5432"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: callbot
      POSTGRES_PASSWORD: callbot
      POSTGRES_DB: maindb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
  postgres-data:

  # pgadmin:
  #   container_name: pgadmin-container
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Replace with your desired email
  #     PGADMIN_DEFAULT_PASSWORD: admin        # Replace with your desired password
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"

